name: Copy README.md to organization profile

on:
  workflow_dispatch:

  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37

    - name: Copy README.md
      if: contains(steps.changed-files.outputs.modified_files, 'README.md')
      run: |
        echo "README.md file has been modified."
        # Copiar el archivo a los submódulos
        cp README.md /tmp/

        mv /tmp/README.md front
        mv /tmp/README.md back
        cd ./front

        # Volver al directorio raíz
        cd ..

    - name: Show result
      run: echo "README_CHANGED=${{ env.README_CHANGED }}"
