name: Copiar Archivo a Submódulo
env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Verificar Cambios en README
      id: check_changes
      run: |
        CHANGED_README=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep 'README.md' || true)
        if [[ -n "${CHANGED_README}" ]]; then
          echo "README_CHANGED=true" >> $GITHUB_ENV
        fi

    - name: Copiar Archivo a Submódulo
      if: contains(env.CHANGED_FILES, 'archivo-a-copiar.txt')
      run: |
        # Copiar el archivo a la carpeta del submódulo
        cp README.md /tmp/

        # Clonar el repositorio RepoB
        git clone https://${ACCESS_TOKEN}@github.com/sleepy-spider/.github.git organization
        mv /tmp/README.md organization/profile
        cd organization/profile
        
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Copiar archivo a submódulo"
        git push

        # Volver al directorio raíz
        cd ..

    - name: Mostrar Resultado
      run: echo "README_CHANGED=${{ env.README_CHANGED }}"
