name: Pasar tests unitarios

on:
  workflow_dispatch:

  push:
    branches:
      - maingi

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          cd front
          npm install

      - name: Ejecutar tests unitarios
        run: |
          cd front
          npm run test
