name: Pasar tests unitarios

on:
  push:
    - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar dependencias
        run: |
          cd front
          npm install

      - name: Ejecutar tests unitarios
        run: npm run test
